langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEADCS
    
matrix:
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto $TRAVIS_BUILD_DIR

script:
 - raco test $TRAVIS_BUILD_DIR

