langauge: c
env:
  - RACKET_VERSION=6.1.1

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash

script:
 - /usr/racket/bin/raco pkg $TRAVIS_BUILD_DIR
 - /usr/racket/bin/raco test $TRAVIS_BUILD_DIR
 - /usr/racket/bin/raco cover -v -c coveralls -d $TRAVIS_BUILD_DIR/coverage $TRAVIS_BUILD_DIR
