langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEADCS
    - RACKET_VERSION=HEAD
    - if: branch = release
      RACKET_VERSION=HEAD FROM_PKG_SERVER=yes
    - RACKET_VERSION=7.6
    - RACKET_VERSION=7.5
    - RACKET_VERSION=7.4
    - RACKET_VERSION=7.3
    - RACKET_VERSION=7.2
    - RACKET_VERSION=7.1
    - RACKET_VERSION=7.0
    - RACKET_VERSION=6.12
    - RACKET_VERSION=6.11
    - RACKET_VERSION=6.10
    - RACKET_VERSION=6.9
    
matrix:
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - if [ $FROM_PKG_SERVER == "yes" ]; then
      raco pkg install --deps search-auto cover-lib cover-test cover-doc cover cover-benchmarks;
    else
       raco pkg install --deps search-auto $TRAVIS_BUILD_DIR/cover-lib $TRAVIS_BUILD_DIR/cover-doc $TRAVIS_BUILD_DIR/cover-test $TRAVIS_BUILD_DIR/cover $TRAVIS_BUILD_DIR/cover-benchmarks;
    fi
  - raco pkg install cover-codecov

script:
 - raco test -p cover-lib cover-test cover-doc cover 

after_success:
 - raco cover -f codecov -d $TRAVIS_BUILD_DIR/coverage -bp cover-lib cover-test cover-doc cover
