langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=6.2
    - RACKET_VERSION=6.2.1
    - RACKET_VERSION=HEAD
    
matrix:
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto $TRAVIS_BUILD_DIR
  - raco pkg install cover-coveralls

script:
 - raco test -Q $TRAVIS_BUILD_DIR
 - raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage -b $TRAVIS_BUILD_DIR
